name: Build and Push to GHCR 

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and Push the Image to GHCR
        run: |
          docker login -u mercybassey -p ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          docker build -t ghcr.io/mercybassey/hello-world:latest .
          docker push ghcr.io/mercybassey/hello-world:latest    

          